### ISSUE TITLE
How to save MarkdownView as image or HTML file?

### ISSUE THREAD

**Issue by yifeizhou** [falnatsheh/MarkdownView#10]
I need to save my MarkdownView as a picture or HTML file, does anyone know how to do it?

**Comment by DiegoRosado** [comment]
Hi @yifeizhou 

MarkdownView extends from [WebView](http://developer.android.com/reference/android/webkit/WebView.html)

Checking the documentation you can use [public void saveWebArchive (String filename)](http://developer.android.com/reference/android/webkit/WebView.html#saveWebArchive%28java.lang.String%29) method to save the **html** or [public Picture capturePicture ()](http://developer.android.com/reference/android/webkit/WebView.html#capturePicture()) to get a [Picture](http://developer.android.com/reference/android/graphics/Picture.html) but this lastest method is deprecated since API level 19.

I think that [public void saveWebArchive (String filename)](http://developer.android.com/reference/android/webkit/WebView.html#saveWebArchive%28java.lang.String%29) method the may be the best option. Maybe @falnatsheh has a better idea.

**Comment by yifeizhou** [comment]
@DiegoRosado 

Thank you very much！You solve my problem : )

**Comment by falnatsheh** [comment]
Good idea @DiegoRosado. Also MarkdownView is using "MarkdownJ", so you could basicly do: 
```java
import com.petebevin.markdown.MarkdownProcessor;
...
String htmlOutput = new MarkdownProcessor().markdown(markdownText);
// Save 'htmlOutput' to a file
```

**Comment by yifeizhou** [comment]
@falnatsheh 
Thank you very much~
