### ISSUE TITLE
How scale image (without horizontal scrolling)?

### ISSUE THREAD

**Issue by alexei28** [falnatsheh/MarkdownView#33]
My layout xml:

`    <us.feras.mdv.MarkdownView
        android:id="@+id/markdownView"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />`

My code:

`public class MarkdownViewActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.markdown_view_activity);

        MarkdownView markdownViewFeras = (MarkdownView) findViewById(R.id.markdownView_Feras);
        markdownViewFeras.loadMarkdownFile("file:///android_asset/my.md" );
    }
}`

OK. It's work. 

But has problem only with image. The image is horizontal scrolling. But I need to  scale image (without horizontal scrolling). Is it possible?

**Comment by falnatsheh** [comment]
Yeah it is possible. Since it's just a Webview you could add your custom css tool to scale images based on your need. Take a look [here](https://github.com/falnatsheh/MarkdownView#theming) to see how you could add css file to MarkdownView, and you could easily find examples on how to scale images using css on the web like [this link](http://wpbeaches.com/make-images-scale-responsive-web-design/) for example.

**Comment by alexei28** [comment]
Thanks. I use (in html) this to fix proble:

`<meta name="viewport" content="width=device-width, initial-scale=1">`
